### ISSUE TITLE
create / view an entry

### ISSUE THREAD

**Issue by DAC098** [ChicoState/GoodDays#6]
along with the table to view all entries we will need a way to view a specific entry to see all data attached to it or the ability to make changes to it. this part can also encompass the ability to create new entries that will be saved for the user.

**Comment by clmcguire** [comment]
Is this for going back and editing old entries? or for viewing older entries and getting a summary of what was inputted? I guess I am wondering if this pertains more to data entry or viewing data from past entries.

**Comment by DAC098** [comment]
@clmcguire the page could serve multiple purposes.
1. the page would serve as a way to input new entries for the user allowing them to specify the date, title, content (any additional texted based information), and mood.
2. viewing an existing entry to see all data attached to it. anything that is not shown on the table, calendar, graphs, etc.
3. when viewing an existing entry you could hit an edit button and make changes as needed and then save those changes.

for now, this could just be a form with the inputs disabled when viewing an existing entry and then have the inputs enabled when creating / editing.
